name: quitter
description: "Quit addictions with Free and Open Source software"
publish_to: 'none'
version: 1.0.92+94
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  dynamic_color: ^1.8.1
  flutter_svg: ^2.2.2
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  workmanager: ^0.9.0+3
  url_launcher: ^6.3.2
  msix: ^3.16.12
  package_info_plus: ^9.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  file_picker: ^10.3.6
  uuid: ^4.5.2
  share_plus: ^12.0.1
  home_widget: ^0.8.1
  crypto: ^3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 # Add this line
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/changelogs/
msix_config:
  msstore_appId: 9PKVZWDG3FGC
  display_name: Quitter - Addiction recovery tracker
  publisher_display_name: Brandon Dick
  identity_name: FrisbeeSoftware.Quitter-Addictionrecoverytracker
  msix_version: 1.0.79.0
  logo_path: assets/icon.png
  trim_logo: false
  publisher: CN=BB0811CB-EED5-441C-BE1B-D31F391F76DE
  store: true
